name: "runn with run:exec"
on:
  pull_request: ~

jobs:
  runn-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: k2tzumi/runn-action@latest
        with:
          command: run
          path_pattern: *.yml
          verbose: true
          enable-run-exec-scope: true
